type GalleryItem {
  id: String!
  title: String!
  description: String
  content: String
  imagePath: String
  remoteObject: [String!]
  createdAt: DateTime
  updatedAt: DateTime
}

input GalleryItemInput {
  title: String!
  description: String
  content: String
  imagePath: String
  remoteObject: [String!]
}

type GalleryQueries {
  list: [GalleryItem]
  locate(id: ID!): GalleryItem
  listByRemoteObjects(ids: [String!]!): [GalleryItem]
}

type CreateGalleryItemResponse {
  message: String!
  item: GalleryItem!
}

type GalleryMutations {
  create(input: GalleryItemInput): CreateGalleryItemResponse!
}

extend type Query {
  galleryQueries: GalleryQueries!
}

extend type Mutation {
  galleryMutations: GalleryMutations!
}
