type Person {
  id: String!
  firstName: String!
  lastName: String!
  displayName: String
  title: String
  email: String
  phone: String
  place: Place
  createdAt: DateTime
  updatedAt: DateTime
}

type Place {
  id: String!
  line1: String
  line2: String
  city: String
  region: String
  postalCode: String
  country: String
}

input PersonInput {
  id: ID
  firstName: String!
  lastName: String!
  displayName: String
  title: String
  email: String
  phone: String
  placeId: ID
}

input PlaceInput {
  id: ID
  line1: String
  line2: String
  city: String
  region: String
  postalCode: String
  country: String
}

type FatesQueries {
  person(id: ID!): Person
  listPeople: [Person!]
  place(id: ID!): Place
  listPlaces: [Place!]
}

type CreatePersonResponse {
  message: String!
  person: Person!
}

type SavePersonResponse {
  message: String!
  person: Person!
}

type DeletePersonResponse {
  message: String!
  id: ID!
}

type CreatePlaceResponse {
  message: String!
  place: Place!
}

type SavePlaceResponse {
  message: String!
  place: Place!
}

type DeletePlaceResponse {
  message: String!
  id: ID!
}

type FatesMutations {
  createPerson(input: PersonInput!): CreatePersonResponse!
  savePerson(input: PersonInput!): SavePersonResponse!
  deletePerson(id: ID!): DeletePersonResponse!
  createPlace(input: PlaceInput!): CreatePlaceResponse!
  savePlace(input: PlaceInput!): SavePlaceResponse!
  deletePlace(id: ID!): DeletePlaceResponse!
}

extend type Query {
  fatesQueries: FatesQueries!
}

extend type Mutation {
  fatesMutations: FatesMutations!
}
